# Generated by Django 5.1.3 on 2024-11-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pH', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('phosphate', models.FloatField()),
                ('total_organic_carbon', models.FloatField()),
                ('chlorine', models.FloatField()),
                ('ammonium', models.FloatField()),
                ('heavy_metals', models.FloatField()),
                ('fluoride', models.FloatField()),
                ('oxidation_reduction_potential', models.FloatField()),
                ('biological_oxygen_demand', models.FloatField()),
            ],
        ),
    ]
